bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: AQu/5cBFpAVlO7X/fYJxzGZTPTV5gaOAbvZCgrOL2zVuDkKlapUaEIDBgoy0q7NyaF2ZHRJlKDi34tv9IUBvceDn3GLyA0s0Gw+ZUdVsmArnpcz2YUiVh5mw1I4f/v6RnGYVJmn87A3L71fExBNaH8KkF2KNct7ztG5ttX16AX320PyTZf0GfSyKvfrUgHX2xmZ5FqW1jjUC01p7qwPJbSBQHBs62t/EY5jh+P+ofaqUH/8EbzisyDQffuYwffY9oE2fu6JhY05xcstsWYEIz2Y3Ke3CuEACYtUb9Zt086KPa3UYQMdo0fG/+6JfpI52n+DpObEvpWA7NTmaTrhps53LES1a7PhtiAI5efwR/ZfnP0pxgAoORnMMZq2adf8ezFkjB/JBXYUU4iCBgBCQmuXEh/JGJ7Av9MDCr58ivTSjEM2SCXzB8ZS3dTLSHUAcUL5aV4F8qccFbduP191CPBh/WJKpkmmrgyGdjYpVAQ/rqhkjSavlANeVPbuxMPu1+B3Lo09vjdbYI0ydbf7ld20XBePx/k5kNMYKEFRkRA1kZO3Eqtby4EW6X/FFw6/gXx7HNKrEDl2c35QEreMC0GsuiWa2sRX0u1TxskTjouKYwE85CtHuwyJDL7zCXZBZRy0mk5bhzPUdOTk+5aLpqsGMaIZlLZ9FN5BjRlmrO4Q=
conda_forge_output_validation: true
